### ISSUE TITLE
care plan spontaneous encounter not visible

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#151]
ist klar -keine Order; trotzdem, wäre das gut?

**Comment by pherk** [comment]
- implementable as OutcomeReference with inline request (fhir:detail)
- so far only, if active CP exists (otherwise complicated)
- CarePlan has to be adapted for reference/detail duality (tricky)
newEncounter.xml:
1. show active CPs
2. select CP an insert new activity, populate inline request properties (fhir:detail)
3. show empty Encounter
4. edit Encounter
5. submit Encounter to get ID
6. set outcomeReference 
7. submit CP and unload form

**Comment by pherk** [comment]
- implemented, further improvs after user feedback
- display reason = outcome in list?
- a little bit tested, seems to be ok ;-)
